name: Basic CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


env:
  APP_NAME: github-actions-docker-cicd
  NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read environment name from GitHub Secret
        run: echo "Deployment environment is configured from GitHub secrets"

      - name: Validate environment secret exists
        env:
          ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
        run: |
          if [ -z "$ENVIRONMENT_NAME" ]; then
            echo "ENVIRONMENT_NAME secret is missing"
            exit 1
          fi

          echo "ENVIRONMENT_NAME secret is configured"
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Message for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This workflow is running on main branch"

      - name: Message for pull pull_request
        if: github.event_name == 'pull_request'
        run: echo "This workflow is running for a pull request"

  Docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image.
        run: docker build -t $APP_NAME:${{ github.sha }} -t $APP_NAME:latest .

      - name: List Docker images
        run: docker images

      - name: Run Docker container
        run: docker run --rm $APP_NAME:${{ github.sha }}

  summary:
    runs-on: ubuntu-latest
    needs: Docker-build

    steps:
      - name: Create CI summary repositort
        run: |
          mkdir -p reports
          echo "CI pipeline completed successfully" > reports/ci-summary.txt
          echo "Repository: $GITHUB_REPOSITORY" >> reports/ci-summary.txt
          echo "Commit SHA: $GITHUB_SHA" >> reports/ci-summary.txt
          echo "Workflow: $GITHUB_WORKFLOW" >> reports/ci-summary.txt

      - name: Upload CI summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ci-summary-report
          path: reports/ci-summary.txt
         