name: Basic CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:


env:
  APP_NAME: github-actions-docker-cicd
  NODE_VERSION: '22'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image.
        run: docker build -t $APP_NAME:${{ github.sha }} .
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Message for main branch
        if: github.ref == 'refs/heads/main'
        run: echo "This workflow is running on main branch"

      - name: Message for pull pull_request
        if: github.event_name == 'pull_request'
        run: echo "This workflow is running for a pull request"


  summary:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Complete workflow
        run: echo "Basic CI workflow completed successfully"